/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Vlad Zaichyk (https://sketchfab.com/vladzaichyk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-fox-01674a892f414c0681afdeb563cc8e13
Title: Lowpoly fox
*/

import React, { useRef, useEffect, useCallback } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import foxScene from '../assets/3d/lowpoly_fox.glb';
import { a } from '@react-spring/three';

const LowpolyFox = ({ isRotating, setIsRotating, setCurrentStage,currentFocusPoint, ...props }) => {
  const foxRef = useRef();
  const { camera,gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(foxScene);
  const zoomRef = useRef(20);
  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = useCallback((e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);
    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;
  }, [setIsRotating]);

  const handlePointerUp = useCallback((e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  }, [setIsRotating]);

  const handlePointerMove = useCallback((e) => {
    e.stopPropagation();
    e.preventDefault();
    if (!isRotating) return;
    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    const delta = (clientX - lastX.current) / viewport.width;
    foxRef.current.rotation.y += delta * 0.01 * Math.PI;
    lastX.current = clientX;
    rotationSpeed.current = delta * 0.01 * Math.PI;
  }, [isRotating, viewport.width]);

  const handleKeyDown = useCallback((e) => {
    if (e.key === 'ArrowLeft') {
      if (!isRotating) setIsRotating(true);
      foxRef.current.rotation.y += 0.05 * Math.PI;
      rotationSpeed.current = 0.007;
    } else if (e.key === 'ArrowRight') {
      if (!isRotating) setIsRotating(true);
      foxRef.current.rotation.y -= 0.05 * Math.PI;
      rotationSpeed.current = -0.007;
    }
  }, [isRotating, setIsRotating]);

  const handleKeyUp = useCallback((e) => {
    if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
      setIsRotating(false);
    }
  }, [setIsRotating]);

  const handleWheel = useCallback((e) => {
    zoomRef.current += e.deltaY * 0.01; // smooth scroll
    zoomRef.current = Math.min(Math.max(zoomRef.current, 1), 30); // clamp zoom
    camera.position.z = zoomRef.current;
  }, [gl]);
  
  useFrame(() => {
    const rotation = foxRef.current.rotation.y;
    const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

    switch (true) {
      case normalizedRotation >= 5.6 || normalizedRotation <= 0.2:
        setCurrentStage(1); // Hi
        break;
      case normalizedRotation >= 3.8 && normalizedRotation <= 4.4:
        setCurrentStage(2); // About Me 
        break;
      case normalizedRotation >= 2.0 && normalizedRotation <= 2.6:
        setCurrentStage(3); // Projects 
        break;
      case normalizedRotation >= 0.6 && normalizedRotation <= 1.2:
        setCurrentStage(4); // Contact
        break;
      default:
        setCurrentStage(null);
    }
    
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      } else {
        foxRef.current.rotation.y += rotationSpeed.current;
      }
    }
  });

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener('pointerdown', handlePointerDown);
    canvas.addEventListener('pointerup', handlePointerUp);
    canvas.addEventListener('pointermove', handlePointerMove);
    canvas.addEventListener('touchstart', handlePointerDown);
    canvas.addEventListener('touchend', handlePointerUp);
    canvas.addEventListener('touchmove', handlePointerMove);
    window.addEventListener('keydown', handleKeyDown);
    window.addEventListener('keyup', handleKeyUp);
    window.addEventListener('wheel', handleWheel, { passive: false });


    return () => {
      canvas.removeEventListener('pointerdown', handlePointerDown);
      canvas.removeEventListener('pointerup', handlePointerUp);
      canvas.removeEventListener('pointermove', handlePointerMove);
      canvas.removeEventListener('touchstart', handlePointerDown);
      canvas.removeEventListener('touchend', handlePointerUp);
      canvas.removeEventListener('touchmove', handlePointerMove);
      window.removeEventListener('keydown', handleKeyDown);
      window.removeEventListener('keyup', handleKeyUp);
      window.removeEventListener('wheel', handleWheel);

    };
  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove, handleKeyDown, handleKeyUp,handleWheel]);

  return (
    <a.group ref={foxRef} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Fox_by_vladhad22@gmailcom_0'].geometry}
          material={materials['Material.001']}
          position={[0.56, -2.475, 1.051]}
          rotation={[0.06, -0.026, -0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_0.geometry}
          material={materials['Material.002']}
          scale={8.404}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_0.geometry}
          material={materials.Material}
          position={[0.226, 6.994, 0.63]}
          rotation={[0, 0, -1.07]}
          scale={0.905}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere_0.geometry}
          material={materials['Material.003']}
          position={[1.065, 8.218, 7.473]}
          scale={[6.285, 6.285, 3.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere001_0.geometry}
          material={materials['Material.007']}
          position={[-69.608, 16.053, 18.229]}
          scale={5.95}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_0.geometry}
          material={materials['Material.009']}
          position={[-30.238, 20.068, -0.925]}
          rotation={[0, 0, 0.585]}
          scale={9.607}
        />
      </group>
    </a.group>
  );
}

export default LowpolyFox;
