/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: skybox3dArchitect (https://sketchfab.com/skybox3dArchitect)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skybox-clouds-in-the-sky-spatial-io-c7cac39cba83447eab8c6c90116ee1fc
Title: Skybox Clouds in the Sky spatial io
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import skyBox from '../assets/3d/skybox.glb'

export function SkyBox({ isRotating }) {
  const skyRef = useRef()
  const { nodes, materials } = useGLTF(skyBox)

  useFrame((_, delta) => {
    if (isRotating && skyRef.current) {
      skyRef.current.rotation.y += 0.25 * delta
    }
  })

  return (
    <group ref={skyRef} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Skybox_mat}
      />
    </group>
  )
}

export default SkyBox
